language: ruby
cache:
  bundler: true
  directories:
    - tmp/rubocop_cache
    - node_modules
sudo: false
branches:
  only: master
env:
  matrix:
    - TASK='assets:precompile'
    - TASK='brakeman'
    - TASK='rubocop'
    - TASK='flay'
    - TASK='bundle_audit'
    - PLUGINS='' DATABASE_URL=mysql2://travis@127.0.0.1/samson_test BUNDLE_WITHOUT=postgres:sqlite USE_UTF8MB4=1 SILENCE_MIGRATIONS=1 TASK='db:create test:migrate_without_plugins'
    - DATABASE_URL=mysql2://travis@127.0.0.1/samson_test BUNDLE_WITHOUT=postgres:sqlite USE_UTF8MB4=1 SILENCE_MIGRATIONS=1 TASK='db:create db:migrate default'
    - DATABASE_URL=postgresql://postgres@127.0.0.1/samson_test BUNDLE_WITHOUT=mysql:sqlite SILENCE_MIGRATIONS=1 TASK='db:create db:migrate default'
    - DATABASE_URL=sqlite3://null$PWD/db/test.sqlite3 BUNDLE_WITHOUT=postgres:mysql SILENCE_MIGRATIONS=1 TASK='db:create db:migrate default'
before_install: gem install bundler
before_script:
  - mysql -u root -e 'set GLOBAL innodb_large_prefix = true'
  - mysql -u root -e 'set GLOBAL innodb_file_per_table = true'
  - mysql -u root -e 'set GLOBAL innodb_file_format = "barracuda"'
  - mysql -u root -e 'GRANT ALL ON *.* TO 'travis'@'localhost';'
script: bundle exec rake $TASK

# make sure we can release as apache v2
matrix:
  include:
    - env: TASK=fossa # nice label for UI
      before_script:
        - export LOCAL=true && curl -H 'Cache-Control:no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      script:
        - ./fossa analyze --config config/fossa.yml # analyze dependencies and upload them (fails when missing api key)
        - travis_wait 20 ./fossa test --config config/fossa.yml # wait for fossa to analyse the upload and fail if it finds issues, to add ignores contact legal@zendesk.com with subject "FOSSA ignore <NAME> in samson"
